Added recommendation
MLH-Fellowship/prep-project-22.P3.1 pull request #48
Opened 2022-04-18 11:14 UTC by unnati914

solves #19 
![image](https://user-images.githubusercontent.com/69121168/163800456-438c2bcd-7624-40cb-bf2e-41bce9526dec.png)

2022-04-18 12:19 UTC, yashika51 requested changes

2022-04-18 12:19 UTC, yashika51 commented on .eslintcache
> +[{"C:\\Users\\DELL\\OneDrive\\Desktop\\prep-project\\prep-project-22.P3.1\\src\\index.js":"1","C:\\Users\\DELL\\OneDrive\\Desktop\\prep-project\\prep-project-22.P3.1\\src\\App.js":"2","C:\\Users\\DEL
Delete this file :)

2022-04-18 16:58 UTC, PAOK-2001 requested changes
Cool idea! But I don't think it looks good on the weather card itself, I would create another space fot the recomendation. Or perhaps bellowe the bottom info on the card.

2022-04-18 17:16 UTC, unnati914 commented
maybe its minor css changes @PAOK-2001 , if we want it on weather card

2022-04-18 20:02 UTC, PAOK-2001 commented
@unnati914 it seems this changes got pushed in your other PR. I'll try and move the style and I'll make a PR

2022-04-19 17:48 UTC, yashika51 commented
@unnati914 , @PAOK-2001 can this PR be closed?

2022-04-19 17:51 UTC, unnati914 commented
yes, ig we can create a new PR for this

2022-04-19 17:52 UTC, unnati914 commented
closing this

2022-04-19 17:54 UTC, Mayank17M commented
#52 fixes this

2022-04-19 17:55 UTC, closed without merging